#!/bin/bash

### BEGIN INIT INFO

# Provides:			stats_daemon

# Required-Start:		$local_fs $time

# Required-Stop:		$local_fs $time

# Default-Start:		2 3 4 5

# Default-Stop:		        0 1 6

# Short-Description:	        start stats_daemon on boot

# Description:			start, stop, etc stats daemon

### END INIT INFO

BIN='/usr/bin/stats_daemon'
NAME=$(basename $BIN)
PIDFILE="/var/run/$NAME.pid"

getpid() {
	if [ -e $PIDFILE ]; then
		PID=$(cat $PIDFILE)
		if [ -e /proc/$PID ]; then
			return 1
		else
			rm $PIDFILE
		fi
	fi
	return 0
}

start() {
	getpid
	if [ $? -ne 0 ]; then
		echo $NAME is already running [$PID]
		exit
	fi

	echo -n "starting $NAME... "
	$BIN &

	sleep 1
	PID=$(ps --format=pid,cmd -e | grep /usr/bin/stats_daemon | grep -v grep | cut -f1 -d' ')
        echo -n $PID > $PIDFILE
	echo [$PID]
}

stop() {
	getpid
	if [ $? -eq 0 ]; then
		echo $NAME not running
	else
		echo -n "stoping $NAME... "

		kill $PID && rm $PIDFILE && echo done
	fi
}

status() {
	getpid
	if [ $? -eq 0 ]; then
		echo $NAME is not running
	else
		echo $NAME is running [$PID]
	fi
}

restart() {
	echo "restarting $NAME..."
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	status)
		status
	;;
	restart)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
	;;
esac

exit 0
